# Generated by Django 6.1.1 on 2026-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0002_personalpicture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('callcenter', 'کال سنتر'), ('CEO', 'مدیر'), ('marketing', 'مارکتینگ'), ('doctor', 'دکتر'), ('reception', 'پذیرش'), ('photographer', 'عکاس'), ('Assistant_Manager', 'مدیر بالینی'), ('Assistant', 'دستیار')], null=True),
        ),
        migrations.DeleteModel(
            name='CallCenter',
        ),
    ]
