# Generated by Django 6.1.1 on 2026-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0003_users_role_delete_callcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('callcenter', 'کال سنتر'), ('CEO', 'مدیر'), ('marketing', 'مارکتینگ'), ('doctor', 'دکتر'), ('reception', 'پذیرش'), ('photographer', 'عکاس'), ('Assistant_Manager', 'مدیر بالینی'), ('Assistant', 'دستیار'), ('Consent', 'مشاوره')], null=True),
        ),
    ]
