# Generated by Django 6.1.1 on 2026-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0005_submitconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitpersonal',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
