# Generated by Django 6.1.1 on 2026-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0006_alter_submitpersonal_explain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='submitconsent',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
