# Generated by Django 6.1.1 on 2026-10-10 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_station', '0007_abcentpatient_alter_submitconsent_explain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('file', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reserve_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='whoisAsistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='reserve_station.asistant')),
            ],
        ),
    ]
